### ISSUE TITLE
Remove validity check for directives

### ISSUE THREAD

**Issue by Schepp** [hyperia-sk/yii2-secure-headers#13]
Hey there! First and foremost, thank you for making this package available.

There is a problem with your approach of dropping the creation of the whole policy header when one directive is unknown. The thing is there are constanly [new directives popping up](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy) and then there are older ones which you haven't allow-listed yet, like [`child-src`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/child-src) or [`frame-ancestors`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors) which, when added, turn off CSP altogether as a result.

My suggestion would be to remove the validity check altogether, as it doesn't bring any advantages, only the opposite. The only browser breaking when CSP has invalid bits is [old Edge](https://portswigger.net/research/bypassing-csp-with-policy-injection), which almost nobody uses and which implements a behavior not intended for CSP.

**Comment by karster** [comment]
Hello,

we are happy that you like our package.

To your proposal. I absolutely agree that CSP validator is not necessary and is removed in version 2.1.1.
