### ISSUE TITLE
Let users freely define the reporting URL

### ISSUE THREAD

**Issue by Schepp** [hyperia-sk/yii2-secure-headers#15]
Right know, when configuring the report URL, the library always appends a `/r/d/csp/enforce`. Even if it seems like a mostly agreed on standard, it doesn't work for services like Sentry.io. It is also not the agreed upon standard for the Report-Only mode, see [Issue #14](https://github.com/hyperia-sk/yii2-secure-headers/issues/14), where it is `/r/d/csp/reportOnly`.

It would be better to just spit out what gets configured by the user without appending anything extra.

**Comment by karster** [comment]
From version 2.1.1 Developer can add custom report URI without adding anything extra to URL. Thank you for suggestion.
