### ISSUE TITLE
Chrome Console

### ISSUE THREAD

**Issue by acs-ferreira** [hyperia-sk/yii2-secure-headers#2]
> Error parsing header X-XSS-Protection: 1; mode=block; report=https://mycompany.report-uri.io/, 1; mode=block: expected semicolon at character position 57. The default protections will be applied.

`mode=block` is repeated twice and last one ends with `:` instead of `;`

**Comment by arzzen** [comment]
fixed in #3

**Comment by karster** [comment]
@acs-ferreira thank you for reporting.
Probably you have set X-XSS-Protection header in your Apache or Nginx configuration. We fixed this issue by adding new option to disable xss protection in package configuration
